# Generated by Django 4.1.7 on 2026-02-22 06:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('RUN', 'Running'), ('WALK', 'Walking'), ('CYCLE', 'Cycling'), ('SWIM', 'Swimming'), ('YOGA', 'Yoga'), ('STRENGTH', 'Strength Training'), ('OTHER', 'Other')], max_length=20)),
                ('duration_minutes', models.IntegerField()),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='profiles.profile')),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-date'],
            },
        ),
    ]
